# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10d63e516f4a740fba435f765b4ab6c1973019a073b24150d46de4c3d1bbb631aefe3678c1d7c0e13eabdeb8babc069c36d91db0832c584adcec83d59b3daab9

test:
  secret_key_base: 3f6887a128fb17e6031db026d1d6d3b5aff9ee04e297090b076a3b9ed59a547a9565218ca212881971b4ef370e4966b0a19fb6053b2158e629f1a0da7b3ad64f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
